# Generated by Django 3.2.16 on 2023-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='pids',
            field=models.ManyToManyField(blank=True, related_name='_family_tree_manager_familytree_pids_+', to='family_tree_manager.FamilyTree'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='relationship',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
