# Generated by Django 4.1 on 2023-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0002_auto_20230515_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='pids',
            field=models.ManyToManyField(blank=True, related_name='parents', to='family_tree_manager.familytree'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
