# Generated by Django 4.1 on 2023-05-26 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0004_alter_familytree_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familytree',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familytree',
            name='family_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familytree',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familytree',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^\\+?0\\d{9,10}$')]),
        ),
    ]
