# Generated by Django 4.1 on 2023-05-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0005_familytree_address_familytree_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familytree',
            name='relationship',
        ),
    ]
