# Generated by Django 4.1 on 2023-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0007_familytree_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
