# Generated by Django 4.1 on 2023-05-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0008_familytree_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familytree',
            name='is_admin',
        ),
    ]
