# Generated by Django 4.1 on 2023-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0010_familytree_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familytree',
            name='education',
            field=models.CharField(blank=True, choices=[('none', 'Không có'), ('elementary', 'Tiểu học'), ('middle_school', 'Trung học cơ sở'), ('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('engineer', 'Kỹ sư'), ('doctorate', 'Tiến sĩ'), ('master', 'Thạc sĩ')], default='none', max_length=20, null=True),
        ),
    ]
