# Generated by Django 4.1 on 2023-06-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0011_familytree_achievement_familytree_education'),
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family_tree_manager.familytree'),
        ),
    ]
