# Generated by Django 4.1 on 2023-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionlevel',
            name='name',
        ),
        migrations.AddField(
            model_name='contributionlevel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributionlevel',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
