# Generated by Django 4.1 on 2023-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0007_remove_contributionlevel_name_contributionlevel_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionlevel',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
