# Generated by Django 4.1 on 2023-06-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree_manager', '0011_familytree_achievement_familytree_education'),
        ('financial_management', '0008_alter_contributionlevel_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('sponsor', 'member')},
        ),
    ]
