# Generated by Django 4.1 on 2023-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0010_alter_income_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
